name: PR Test
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: rh-rluong/hello-world-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
